apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosaic-server
  labels:
    app.kubernetes.io/name: mosaic-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mosaic-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosaic-server
    spec:
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: mosaic
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3010
              name: http
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 20
