apiVersion: v1
kind: Service
metadata:
  name: mosaic-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: mosaic-server
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
---
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mosaic-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mosaic-server
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
